// admin/src/assets/dummyStyles.ts — AROHAK Brand: Crimson Red · Gold · Light

export const dashboardStyles = {
  pageContainer: "min-h-screen pt-25 bg-gradient-to-br from-white via-red-50/30 to-amber-50/20 font-sans relative",
  backgroundPattern: "",
  contentContainer: "relative z-10 container mx-auto px-4 sm:px-6 lg:px-12 py-10",
  headerContainer: "mb-10 text-center sm:text-left",
  headerTitle: "text-4xl sm:text-5xl lg:text-6xl font-extrabold text-gray-900 mb-2 tracking-tight",
  headerSubtitle: "text-gray-500 text-base sm:text-lg font-medium",
  statsGrid: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mb-10",
  statCard: "bg-white rounded-2xl p-5 sm:p-6 border border-red-100 hover:border-red-300 hover:shadow-2xl hover:shadow-red-500/10 hover:-translate-y-1 transition-all duration-300",
  statTitle: "text-gray-500 text-xs font-bold uppercase tracking-wider mb-1",
  statValue: "text-3xl sm:text-4xl font-extrabold text-gray-900 mt-1",
  statIconContainer: (color) => {
    const map = {
      indigo: "bg-gradient-to-br from-red-600 to-amber-500 text-white",
      green: "bg-gradient-to-br from-emerald-400 to-emerald-600 text-white",
      yellow: "bg-gradient-to-br from-amber-500 to-red-500 text-white",
      purple: "bg-gradient-to-br from-red-700 to-amber-600 text-white",
    };
    return `${map[color] || "bg-gradient-to-br from-red-600 to-amber-500 text-white"} p-3 rounded-xl shadow-lg`;
  },
  statIcon: "w-5 h-5 sm:w-6 sm:h-6",
  coursesContainer: "bg-white rounded-2xl border border-red-100 overflow-hidden shadow-xl",
  coursesHeader: "px-4 sm:px-6 py-5 border-b border-red-100 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4",
  coursesTitleContainer: "flex items-center",
  coursesIcon: "w-5 h-5 mr-2 text-red-600",
  coursesTitle: "text-lg sm:text-xl font-extrabold text-gray-900 tracking-tight",
  searchContainer: "relative w-full sm:w-auto",
  searchIcon: "w-4 h-4 text-gray-400 absolute left-3.5 top-1/2 transform -translate-y-1/2",
  searchInput: "pl-10 pr-4 py-2.5 border border-red-100 rounded-xl focus:outline-none focus:ring-2 focus:ring-red-500/25 focus:border-red-500 w-full sm:w-64 text-sm bg-white text-gray-900 placeholder-gray-400",
  tableContainer: "overflow-x-auto",
  table: "min-w-full",
  tableHead: "bg-gradient-to-r from-red-50 to-amber-50 border-b border-red-100",
  tableHeader: "px-4 sm:px-6 py-3 text-left text-xs font-bold text-gray-600 uppercase tracking-wider",
  tableBody: "divide-y divide-red-50",
  tableRow: "hover:bg-red-50/40 transition-colors duration-150",
  courseImage: "w-10 h-8 sm:w-12 sm:h-10 rounded-xl object-cover mr-3 sm:mr-4 shadow-md",
  courseName: "font-bold text-gray-900 text-sm sm:text-base",
  courseInstructor: "text-xs sm:text-sm text-gray-500 mt-0.5",
  studentsCell: "px-4 sm:px-6 py-3 sm:py-4",
  studentsText: "font-semibold text-sm sm:text-base text-gray-700",
  priceCell: "px-4 sm:px-6 py-3 sm:py-4 text-white font-bold text-sm sm:text-base",
  purchasesContainer: "flex items-center text-gray-700",
  purchasesIcon: "w-4 h-4 mr-2 text-emerald-500",
  purchasesText: "text-sm sm:text-base font-semibold",
  earningsCell: "px-4 sm:px-6 py-3 sm:py-4 text-emerald-500 font-bold text-sm sm:text-base",
  loadingOverlay: "flex items-center justify-center py-16",
  loadingSpinner: "w-8 h-8 border-4 border-red-100 border-t-red-600 rounded-full animate-spin",
  errorBanner: "mb-6 px-4 py-3 bg-red-50 border border-red-200 text-red-600 rounded-xl text-sm",
  emptyState: "text-center py-14",
  emptyIcon: "w-12 h-12 text-gray-300 mx-auto mb-4",
  emptyText: "text-gray-500 text-base sm:text-lg",
  clearButton: "mt-2 text-red-600 hover:text-red-700 font-bold text-sm"
};

export const listStyles = {
  pageContainer: "min-h-screen bg-gradient-to-br from-white via-red-50/30 to-amber-50/20 py-6 sm:py-8 lg:py-10 px-3 sm:px-4 lg:px-6",
  contentContainer: "max-w-6xl pt-20 sm:pt-24 lg:pt-25 mx-auto",
  headerContainer: "text-center mb-8 sm:mb-10",
  headerTitle: "text-4xl sm:text-5xl font-extrabold text-gray-900 mb-1 tracking-tight",
  headerSubtitle: "text-gray-500 text-sm sm:text-base font-medium",
  searchContainer: "mb-8",
  searchInputContainer: "relative max-w-md mx-auto",
  searchIcon: "w-4 h-4 sm:w-5 sm:h-5 text-gray-400 absolute left-3.5 top-1/2 transform -translate-y-1/2",
  searchInput: "w-full pl-10 sm:pl-11 pr-4 py-3 border border-red-100 rounded-2xl focus:outline-none focus:ring-2 focus:ring-red-500/25 focus:border-red-500 bg-white text-gray-900 placeholder-gray-400 text-sm sm:text-base shadow-sm",
  courseList: "space-y-4",
  courseCard: "bg-white rounded-2xl border border-red-100 hover:border-red-300 hover:shadow-2xl hover:shadow-red-500/10 hover:-translate-y-0.5 transition-all duration-300 overflow-hidden",
  courseCardContent: "p-4 sm:p-6",
  courseHeader: "flex flex-col lg:flex-row lg:items-center lg:justify-between gap-3 sm:gap-4",
  courseImageContainer: "flex items-start gap-3 sm:gap-4 flex-1",
  courseImage: "w-16 h-12 sm:w-20 sm:h-16 lg:w-24 lg:h-16 rounded-xl object-cover shadow-md flex-shrink-0",
  courseInfo: "flex-1 min-w-0",
  courseTitleRow: "flex flex-col sm:flex-row sm:items-start sm:justify-between gap-1 sm:gap-2",
  courseTitle: "text-lg sm:text-xl font-extrabold text-gray-900 mb-1 break-words tracking-tight",
  courseInstructor: "text-gray-500 text-sm sm:text-base mb-2 font-medium",
  courseBadge: (courseType) =>
    `px-2.5 py-0.5 mb-4 text-xs font-bold rounded-full select-none self-start lg:mt-8 xl:mt-8 sm:self-auto uppercase tracking-wider ${
      courseType === 'top'
        ? 'bg-gradient-to-r from-red-600 to-amber-500 text-white shadow-lg'
        : 'bg-gray-100 text-gray-600 border border-gray-200'
    }`,
  courseMeta: "flex flex-wrap items-center gap-2 sm:gap-3 text-xs sm:text-sm text-gray-500",
  metaItem: "flex items-center gap-1",
  metaIcon: "w-3 h-3 sm:w-4 sm:h-4",
  courseActions: "flex items-center justify-between lg:justify-end gap-3 sm:gap-4 mt-2 sm:mt-0",
  priceContainer: "text-right",
  priceFree: "text-xl sm:text-2xl font-bold text-emerald-500",
  priceRegular: "text-xl sm:text-2xl font-bold text-gray-900",
  originalPrice: "text-xs sm:text-sm text-gray-400 line-through",
  actionButtons: "flex items-center gap-1 sm:gap-2",
  toggleButton: "p-1.5 sm:p-2 text-red-600 hover:text-white hover:bg-red-600 rounded-xl cursor-pointer transition-colors duration-200 flex items-center",
  deleteButton: "p-1.5 sm:p-2 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-xl transition-colors duration-200",
  actionIcon: "w-4 h-4 sm:w-5 sm:h-5",
  expandedCourse: "border-t border-red-100 bg-gradient-to-r from-red-50/30 to-amber-50/20 p-4 sm:p-6",
  descriptionSection: "mb-4 sm:mb-6",
  descriptionTitle: "text-base sm:text-lg font-extrabold text-gray-900 mb-2 sm:mb-3 tracking-tight",
  descriptionText: "text-gray-600 leading-relaxed text-sm sm:text-base",
  contentSection: "space-y-2 sm:space-y-3",
  lectureCard: "bg-white rounded-xl border border-red-100 overflow-hidden shadow-sm",
  lectureHeader: "p-3 sm:p-4",
  lectureToggleButton: "flex items-center justify-between w-full text-left gap-2 sm:gap-3",
  lectureInfo: "flex items-center gap-2 sm:gap-3 flex-1 min-w-0",
  lectureTitle: "font-extrabold text-gray-900 text-sm sm:text-base break-words tracking-tight",
  lectureMeta: "flex items-center gap-2 sm:gap-3 text-xs sm:text-sm text-gray-500 mt-1",
  lectureToggleIcon: (isExpanded) =>
    `w-4 h-4 sm:w-5 sm:h-5 text-red-600 cursor-pointer transition-transform duration-200 flex-shrink-0 ${isExpanded ? 'rotate-180' : ''}`,
  expandedLecture: "border-t border-red-100 bg-gradient-to-r from-red-50/20 to-amber-50/10 p-3 sm:p-4",
  chapterList: "space-y-2 sm:space-y-3",
  chapterCard: "flex items-center justify-between p-2 sm:p-3 bg-white rounded-xl border border-red-100 shadow-sm",
  chapterContent: "flex-1 min-w-0",
  chapterHeader: "flex items-start gap-2 sm:gap-3",
  chapterIcon: "p-1.5 sm:p-2 bg-gradient-to-br from-red-600 to-amber-500 rounded-lg flex-shrink-0 mt-0.5",
  chapterIconSvg: "w-3 h-3 sm:w-4 sm:h-4 text-white",
  chapterDetails: "flex-1 min-w-0",
  chapterTitle: "font-extrabold text-gray-900 text-sm sm:text-base break-words hover:underline block",
  chapterTopic: "text-xs sm:text-sm text-gray-500 mt-1 break-words",
  chapterMeta: "flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-3 mt-2 text-xs text-gray-500",
  chapterDuration: "flex items-center gap-1 text-red-600 font-bold",
  chapterVideoLink: "text-red-600 break-all hover:underline",
  emptyState: "text-center py-10 sm:py-14",
  emptyIcon: "w-12 h-12 sm:w-16 sm:h-16 text-gray-300 mx-auto mb-3 sm:mb-4",
  emptyText: "text-gray-500 text-base sm:text-lg mb-2",
  clearButton: "text-red-600 hover:text-red-700 font-bold text-sm sm:text-base",
  starRating: "flex items-center gap-1",
  starFull: "w-3 h-3 sm:w-4 sm:h-4 text-amber-500",
  starHalf: "w-3 h-3 sm:w-4 sm:h-4 text-amber-500",
  starEmpty: "w-3 h-3 sm:w-4 sm:h-4 text-gray-300"
};

export const addPageStyles = {
  pageContainer: "min-h-screen bg-gradient-to-br from-white via-red-50/30 to-amber-50/20 py-4 sm:py-6 lg:py-8 px-3 sm:px-4 lg:px-6",
  contentContainer: "max-w-4xl pt-30 mx-auto",
  headerContainer: "text-center mb-10 sm:mb-12",
  headerGradient: "relative inline-block",
  headerGlow: "",
  headerTitle: "relative text-3xl sm:text-4xl lg:text-5xl font-extrabold text-gray-900 tracking-tight mb-3 sm:mb-4",
  headerSubtitle: "text-base sm:text-lg text-gray-500 max-w-2xl mx-auto px-2",
  form: "space-y-6 sm:space-y-8",
  card: "bg-white rounded-2xl p-5 sm:p-7 lg:p-9 border border-red-100 hover:border-red-300 shadow-xl hover:shadow-2xl hover:shadow-red-500/10 transition-all duration-300",
  courseTypeCard: "",
  courseInfoCard: "",
  lecturesCard: "",
  cardHeader: "flex items-center gap-3 mb-7 sm:mb-9",
  cardIconContainer: "p-2.5 sm:p-3 bg-gradient-to-br from-red-600 to-amber-500 rounded-xl shadow-lg",
  cardIcon: "text-white",
  cardTitle: "text-xl sm:text-2xl font-extrabold text-gray-900 tracking-tight",
  cardSubtitle: "text-sm sm:text-base text-gray-500",
  courseTypeGrid: "grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-5",
  courseTypeLabel: (isSelected, type) =>
    `flex items-center gap-3 p-4 border rounded-2xl cursor-pointer transition-all duration-300 ${
      isSelected
        ? type === 'top'
          ? "border-red-500 bg-gradient-to-r from-red-50 to-amber-50 shadow-lg shadow-red-500/20"
          : "border-amber-500 bg-amber-50 shadow-lg shadow-amber-500/20"
        : "border-gray-200 hover:border-red-300 hover:bg-red-50/50"
    }`,
  courseTypeInput: "w-4 h-4 sm:w-5 sm:h-5 accent-red-600",
  courseTypeText: "text-base sm:text-lg font-bold text-gray-900 flex items-center gap-2",
  formGrid: "grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-5",
  formFullWidth: "lg:col-span-2",
  inputContainer: "space-y-2",
  inputLabel: "text-gray-600 font-bold flex items-center gap-2 text-xs sm:text-sm uppercase tracking-wider",
  inputIcon: "text-red-600",
  input: "w-full px-4 py-3 bg-white border border-red-100 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-500/25 focus:border-red-500 transition-all duration-300 text-sm sm:text-base shadow-sm",
  textarea: "w-full px-4 py-3 bg-white border border-red-100 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-500/25 focus:border-red-500 transition-all duration-300 resize-none text-sm sm:text-base shadow-sm",
  durationGrid: "grid grid-cols-2 gap-2 sm:gap-3",
  durationHelper: "text-xs text-gray-500 mt-1 block",
  durationFormatted: "text-sm text-red-600 font-bold",
  starRating: "flex gap-1",
  starButton: "text-2xl transition-colors duration-200 focus:outline-none hover:scale-110 transform",
  starFull: "text-amber-500 fill-current",
  starEmpty: "text-gray-300 hover:text-amber-500",
  uploadContainer: "flex flex-col sm:flex-row items-start sm:items-center gap-3 sm:gap-4",
  uploadLabel: "flex-1 w-full cursor-pointer group",
  uploadInput: "hidden",
  uploadBox: "w-full px-4 py-4 bg-white border border-dashed border-red-200 rounded-xl text-gray-500 focus:outline-none transition-all duration-300 flex items-center justify-center gap-3 group-hover:border-red-500 group-hover:bg-red-50/50 group-hover:text-red-600 text-sm sm:text-base shadow-sm",
  uploadIcon: "transition-transform group-hover:scale-110",
  imagePreview: "w-16 h-16 sm:w-20 sm:h-20 lg:w-24 lg:h-24 rounded-2xl overflow-hidden border border-red-100 shadow-xl ring-2 ring-red-500/20 flex-shrink-0",
  select: "w-full px-4 py-3 bg-white border border-red-100 rounded-xl text-gray-900 focus:outline-none focus:ring-2 focus:ring-red-500/25 focus:border-red-500 transition-all duration-300 appearance-none text-sm sm:text-base shadow-sm",
  lecturesHeader: "flex flex-col sm:flex-row sm:justify-between sm:items-center gap-4 mb-7",
  addLectureButton: "bg-gradient-to-r from-red-600 to-amber-500 hover:from-red-700 hover:to-amber-600 cursor-pointer text-white px-5 sm:px-7 py-2.5 sm:py-3 rounded-xl font-bold uppercase tracking-wider transition-all duration-300 flex items-center gap-2 shadow-lg text-sm sm:text-base w-full sm:w-auto justify-center",
  lecturesList: "space-y-4",
  lectureCard: "bg-gradient-to-r from-red-50/40 to-amber-50/20 rounded-2xl p-4 sm:p-6 border border-red-100 hover:border-red-300 shadow-sm hover:shadow-xl hover:shadow-red-500/10 transition-all duration-300",
  lectureHeader: "flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3 mb-4",
  lectureContent: "flex items-center gap-3 sm:gap-4 flex-1",
  lectureToggleButton: "p-2 bg-red-100 text-red-600 rounded-xl hover:bg-red-600 hover:text-white cursor-pointer transition-colors duration-200 flex-shrink-0",
  lectureInfo: "flex-1 min-w-0",
  lectureTitle: "text-lg sm:text-xl font-extrabold text-gray-900 break-words tracking-tight",
  lectureMeta: "text-gray-500 flex items-center gap-2 mt-1 text-sm font-medium",
  lectureActions: "flex items-center gap-2 justify-end sm:justify-start",
  addChapterButton: "bg-gradient-to-r from-red-600 to-amber-500 hover:from-red-700 hover:to-amber-600 text-white px-3 sm:px-4 py-1.5 sm:py-2 rounded-xl font-bold uppercase tracking-wider transition-all duration-300 flex items-center gap-2 cursor-pointer text-xs sm:text-sm shadow-lg",
  deleteButton: "p-1.5 sm:p-2 text-gray-400 hover:text-red-500 cursor-pointer hover:bg-red-50 rounded-xl transition-colors duration-200 ml-1 sm:ml-2",
  chaptersContainer: (isExpanded) =>
    `ml-0 sm:ml-10 lg:ml-12 space-y-2 sm:space-y-3 border-l-0 sm:border-l-2 border-red-200 pl-0 sm:pl-4 lg:pl-6 mt-3 sm:mt-0 ${isExpanded ? 'block' : 'hidden'}`,
  chapterCard: "bg-white rounded-xl p-3 sm:p-4 border border-red-100 shadow-sm",
  chapterContent: "flex flex-col sm:flex-row sm:justify-between sm:items-start gap-2",
  chapterInfo: "flex-1 min-w-0",
  chapterTitle: "text-gray-900 font-extrabold text-sm sm:text-base break-words tracking-tight",
  chapterTopic: "text-gray-500 text-xs sm:text-sm mt-1 break-words",
  chapterMeta: "flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-4 mt-2",
  chapterDuration: "text-red-600 text-xs sm:text-sm flex items-center gap-1 font-bold",
  chapterUrl: "text-red-600 text-xs sm:text-sm font-medium break-all max-w-full sm:max-w-xs",
  chapterDeleteButton: "p-1 text-gray-400 hover:text-red-500 cursor-pointer hover:bg-red-50 rounded-xl transition-colors duration-200 ml-0 sm:ml-4 self-end sm:self-auto mt-2 sm:mt-0",
  submitContainer: "text-center",
  submitButton: "bg-gradient-to-r from-red-600 to-amber-500 hover:from-red-700 hover:to-amber-600 cursor-pointer text-white px-10 sm:px-16 lg:px-20 py-4 rounded-2xl font-bold uppercase tracking-wider text-base sm:text-lg transition-all duration-300 shadow-2xl hover:shadow-red-500/40 w-full sm:w-auto",
  saveLectureButton: "bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-600 hover:to-emerald-600 text-white px-5 py-2 rounded-xl font-bold text-sm transition-all duration-200 cursor-pointer",
  removeLectureButton: "p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-xl transition-colors cursor-pointer",
  removeChapterButton: "p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-xl transition-colors cursor-pointer",
  emptyLectures: "text-center text-gray-400 text-sm py-6",
  lectureItemHeader: "flex items-center justify-between gap-2 p-3 bg-red-50 rounded-xl",
  lectureItemTitle: "font-bold text-gray-800 text-sm flex-1 min-w-0 truncate",
  lectureItemMeta: "text-xs text-gray-500 shrink-0",
  lectureToggle: "flex items-center gap-2 flex-1 min-w-0 text-left cursor-pointer",
  chapterForm: "bg-red-50 border border-red-200 rounded-xl p-4 mb-3",
  chapterName: "font-semibold text-gray-800 text-sm truncate",
  modalOverlay: "fixed inset-0 bg-black/70 backdrop-blur-md flex items-center justify-center p-3 sm:p-4 z-50",
  modal: "bg-white rounded-2xl p-5 sm:p-7 lg:p-9 max-w-md w-full shadow-2xl border border-red-100 mx-2",
  modalHeader: "flex items-center gap-3 mb-5 sm:mb-7",
  modalIconContainer: (color) => `p-2.5 ${color} rounded-xl`,
  modalTitle: "text-xl sm:text-2xl font-extrabold text-gray-900 tracking-tight",
  modalContent: "space-y-3 sm:space-y-4",
  modalActions: "flex gap-2 sm:gap-3 pt-4",
  modalButton: "flex-1 py-2.5 sm:py-3 rounded-xl font-bold uppercase tracking-wider transition-all duration-300 flex items-center justify-center gap-2 text-sm sm:text-base",
  modalButtonPrimary: "bg-gradient-to-r from-red-600 to-amber-500 hover:from-red-700 hover:to-amber-600 cursor-pointer text-white shadow-lg",
  modalButtonSecondary: "bg-red-50 text-red-500 hover:bg-red-100 cursor-pointer",
  modalButtonCompact: "flex-1 py-2.5 sm:py-3 rounded-xl font-bold uppercase tracking-wider transition-all duration-300 text-sm sm:text-base",
  modalButtonCompactPrimary: "bg-gradient-to-r from-red-600 to-amber-500 hover:from-red-700 hover:to-amber-600 text-white shadow-lg hover:scale-105 cursor-pointer",
  modalButtonCompactSecondary: "bg-gray-100 hover:bg-gray-200 text-gray-700 cursor-pointer",
  chaptersList: "space-y-2 max-h-24 sm:max-h-32 overflow-y-auto",
  chapterPreview: "bg-red-50 rounded-xl p-2 sm:p-3 text-xs sm:text-sm border border-red-200",
  chapterPreviewTitle: "font-extrabold text-gray-900",
  chapterPreviewDuration: "text-red-600 text-xs font-bold"
};

export const navbarStyles = {
  nav: (isVisible) =>
    `fixed top-5 left-0 right-0 z-50 pointer-events-auto transition-transform duration-500 ease-in-out ${
      isVisible ? "translate-y-0" : "-translate-y-28"
    }`,
  navContainer: "w-full flex justify-center",
  navInner: (isMenuOpen) =>
    `relative w-[92%] sm:w-[90%] md:w-[95%] lg:w-[75%] xl:w-[88%] max-w-6xl mx-auto rounded-2xl px-5 py-3 bg-white/96 backdrop-blur-2xl border border-red-100 shadow-2xl transition-all duration-500`,
  glowEffect: "pointer-events-none absolute -inset-px rounded-2xl bg-gradient-to-r from-red-500/8 via-amber-500/8 to-red-500/8 blur-sm opacity-60",
  navbarContent: "flex items-center justify-between gap-4 relative z-10",
  logoContainer: "flex items-center gap-3 select-none",
  logoImage: "w-10 h-10 object-contain",
  logoText: "text-lg font-extrabold uppercase tracking-tight text-gray-900",
  desktopNav: "hidden md:flex items-center justify-center flex-1",
  desktopNavInner: "inline-flex items-center gap-1 bg-gradient-to-r from-red-50 to-amber-50 rounded-2xl p-1",
  desktopNavItem: (isActive) =>
    `relative flex items-center gap-2 cursor-pointer px-4 py-2 rounded-xl font-bold uppercase tracking-wider text-xs transition-all duration-300 ${
      isActive
        ? 'bg-gradient-to-r from-red-600 to-amber-500 text-white shadow-lg'
        : 'text-gray-600 hover:text-red-600 hover:bg-white'
    }`,
  desktopNavIcon: "w-4 h-4",
  desktopNavText: "text-xs",
  desktopActiveGlow: "",
  mobileToggleContainer: "flex items-center gap-3 md:hidden",
  mobileToggleButton: "w-10 h-10 rounded-xl bg-gradient-to-r from-red-50 to-amber-50 border border-red-100 flex items-center justify-center",
  mobileToggleIcon: "w-5 h-5 text-gray-600",
  mobileMenu: (isMenuOpen) =>
    `md:hidden mt-3 transition-[max-height,opacity] duration-300 ease-in-out overflow-hidden ${
      isMenuOpen ? 'max-h-64 opacity-100' : 'max-h-0 opacity-0'
    }`,
  mobileMenuInner: "flex flex-col gap-1.5",
  mobileMenuItem: (isActive) =>
    `w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-300 font-bold uppercase tracking-wider text-xs ${
      isActive
        ? 'bg-gradient-to-r from-red-600 to-amber-500 text-white shadow-lg'
        : 'bg-gradient-to-r from-red-50 to-amber-50 hover:from-red-100 hover:to-amber-100 text-gray-600 hover:text-red-600'
    }`,
  mobileMenuIcon: "w-5 h-5",
  mobileMenuText: "font-bold"
};

export const bookingsStyles = {
  pageContainer: "min-h-screen pt-28 bg-gradient-to-br from-white via-red-50/30 to-amber-50/20 p-6",
  contentContainer: "max-w-6xl mx-auto",
  headerContainer: "mb-10",
  headerTitle: "text-4xl font-extrabold text-gray-900 mb-1 tracking-tight",
  headerSubtitle: "text-gray-500 text-sm font-medium",
  searchContainer: "mb-8",
  searchInputContainer: "relative max-w-md",
  searchIcon: "absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400 h-4 w-4",
  searchInput: "w-full pl-10 pr-4 py-3 border border-red-100 rounded-xl focus:outline-none focus:ring-2 focus:ring-red-500/25 focus:border-red-500 bg-white text-gray-900 placeholder-gray-400 text-sm shadow-sm",
  bookingsGrid: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5",
  bookingCard: "bg-white rounded-2xl border border-red-100 hover:border-red-300 hover:shadow-2xl hover:shadow-red-500/10 hover:-translate-y-0.5 p-5 transition-all duration-300",
  studentSection: "flex items-center mb-5",
  studentIconContainer: "bg-gradient-to-br from-red-600 to-amber-500 p-2.5 rounded-xl",
  studentIcon: "h-5 w-5 text-white",
  studentInfo: "ml-3",
  studentName: "font-extrabold text-gray-900 text-base leading-tight tracking-tight",
  purchaseDate: "text-xs text-gray-500 mt-0.5 font-medium",
  courseDetails: "space-y-2.5",
  detailItem: "flex items-center",
  detailIcon: "h-4 w-4 text-gray-400 mr-2 flex-shrink-0",
  detailLabel: "text-gray-500 text-sm font-medium",
  detailValue: "ml-1.5 text-gray-700 text-sm truncate",
  priceValue: "ml-1.5 text-emerald-500 font-bold text-sm",
  statusContainer: "mt-4 pt-3 border-t border-red-100",
  statusBadge: "inline-flex items-center px-2.5 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-emerald-50 text-emerald-600 border border-emerald-200",
  loadingState: "text-gray-500 text-sm py-2",
  errorState: "text-red-500 text-sm py-2",
  emptyState: "text-center py-16",
  emptyContainer: "bg-white rounded-2xl p-10 max-w-sm mx-auto border border-red-100 shadow-xl",
  emptyIcon: "h-10 w-10 text-gray-300 mx-auto mb-3",
  emptyTitle: "text-base font-extrabold text-gray-900 mb-1 tracking-tight",
  emptyText: "text-gray-500 text-sm"
};

export const quizAdminStyles = {
  section: "bg-white rounded-2xl p-5 sm:p-7 lg:p-9 border border-red-100 hover:border-red-300 shadow-xl hover:shadow-2xl hover:shadow-red-500/10 transition-all duration-300",
  sectionHeader: "flex items-center gap-3 mb-7",
  sectionIconContainer: "p-2.5 sm:p-3 bg-gradient-to-br from-red-600 to-amber-500 rounded-xl shadow-lg",
  sectionIcon: "text-white",
  sectionTitle: "text-xl sm:text-2xl font-extrabold text-gray-900 tracking-tight",
  sectionSubtitle: "text-sm sm:text-base text-gray-500",
  toggleRow: "flex items-center justify-between mb-6",
  toggleLabel: "text-gray-700 font-bold text-sm uppercase tracking-wider",
  toggleButton: (enabled) =>
    `relative inline-flex h-6 w-11 items-center rounded-full transition-colors duration-300 cursor-pointer ${
      enabled ? 'bg-gradient-to-r from-red-600 to-amber-500' : 'bg-gray-300'
    }`,
  toggleThumb: (enabled) =>
    `inline-block h-4 w-4 transform rounded-full bg-white transition-transform duration-300 shadow-sm ${
      enabled ? 'translate-x-6' : 'translate-x-1'
    }`,
  passingScoreRow: "flex items-center gap-3 mb-6",
  passingScoreLabel: "text-gray-600 font-bold text-xs uppercase tracking-wider",
  passingScoreInput: "w-20 px-3 py-2 bg-white border border-red-100 rounded-xl text-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-red-500/25 focus:border-red-500 shadow-sm",
  passingScoreUnit: "text-gray-600 text-sm font-medium",
  questionsList: "space-y-3 mb-6",
  questionCard: "bg-gradient-to-r from-red-50/40 to-amber-50/20 rounded-xl p-4 border border-red-100",
  questionHeader: "flex items-start justify-between gap-2 mb-3",
  questionText: "text-gray-900 font-extrabold text-sm tracking-tight flex-1",
  questionDeleteBtn: "p-1 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors cursor-pointer",
  questionOptions: "grid grid-cols-2 gap-2",
  questionOption: (isCorrect) =>
    `text-xs px-2.5 py-1.5 rounded-lg font-bold ${
      isCorrect ? 'bg-emerald-100 text-emerald-700 border border-emerald-300' : 'bg-white text-gray-600 border border-gray-200'
    }`,
  addQuestionForm: "bg-gradient-to-r from-red-50/30 to-amber-50/20 rounded-xl p-4 border border-dashed border-red-200 space-y-3",
  addQuestionTitle: "text-gray-600 font-bold text-xs uppercase tracking-wider mb-3",
  questionInput: "w-full px-3.5 py-2.5 bg-white border border-red-100 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-500/25 focus:border-red-500 text-sm shadow-sm",
  optionsGrid: "grid grid-cols-1 sm:grid-cols-2 gap-2",
  optionRow: "flex items-center gap-2",
  optionLabel: "text-gray-600 text-xs font-bold uppercase w-6 flex-shrink-0",
  optionInput: "flex-1 px-3.5 py-2.5 bg-white border border-red-100 rounded-xl text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-500/25 focus:border-red-500 text-sm shadow-sm",
  correctAnswerRow: "flex items-center gap-3",
  correctAnswerLabel: "text-gray-600 font-bold text-xs uppercase tracking-wider",
  correctAnswerSelect: "px-3.5 py-2.5 bg-white border border-red-100 rounded-xl text-gray-900 focus:outline-none focus:ring-2 focus:ring-red-500/25 focus:border-red-500 text-sm shadow-sm",
  addQuestionBtn: "bg-gradient-to-r from-red-600 to-amber-500 hover:from-red-700 hover:to-amber-600 text-white px-5 py-2.5 rounded-xl font-bold uppercase tracking-wider text-xs transition-all duration-300 flex items-center gap-2 cursor-pointer shadow-lg",
  limitNote: "text-gray-500 text-xs font-medium",
};
